//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8794
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JustDecompile.Tools.MSBuildProjectBuilder.NetCore {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Project {
        
        private object[] projectItemsField;
        
        private string sdkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", typeof(ProjectPropertyGroup))]
		[System.Xml.Serialization.XmlElementAttribute("ItemGroup", typeof(ProjectItemGroup))]
		[System.Xml.Serialization.XmlElementAttribute("Import", typeof(ProjectImport))]
		[System.Xml.Serialization.XmlElementAttribute("Target", typeof(ProjectTarget))]

		public object[] Items
		{
            get {
                return this.projectItemsField;
            }
            set {
                this.projectItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sdk {
            get {
                return this.sdkField;
            }
            set {
                this.sdkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectPropertyGroup {
        
        private string defineConstantsField;
        
        private string platformTargetField;
        
        private string allowUnsafeBlocksField;
        
        private bool optimizeField;
        
        private bool optimizeFieldSpecified;
        
        private string treatWarningsAsErrorsField;
        
        private string warningsAsErrorsField;
        
        private string documentationFileField;
        
        private string generateSerializationAssembliesField;
        
        private string checkForOverflowUnderflowField;
        
        private string debugTypeField;
        
        private bool debugSymbolsField;
        
        private bool debugSymbolsFieldSpecified;
        
        private string outputPathField;
        
        private byte warningLevelField;
        
        private bool warningLevelFieldSpecified;
        
        private string outputTypeField;
        
        private string targetFrameworkField;
        
        private string targetFrameworksField;
        
        private string enableDefaultItemsField;
        
        private string signAssemblyField;
        
        private string assemblyOriginatorKeyFileField;
        
        private string applicationManifestField;
        
        private string packageReleaseNotesField;
        
        private string packageTagsField;
        
        private string repositoryTypeField;
        
        private string repositoryUrlField;
        
        private string packageIconUrlField;
        
        private string packageProjectUrlField;
        
        private string packageLicenseUrlField;
        
        private string copyrightField;
        
        private string descriptionField;
        
        private string assemblyVersionField;
        
        private string applicationIconField;
        
        private string generatePackageOnBuildField;
        
        private string packageRequireLicenseAcceptanceField;
        
        private string neutralLanguageField;
        
        private string fileVersionField;
        
        private string mvcRazorCompileOnPublishField;
        
        private string generateAssemblyConfigurationAttributeField;
        
        private string generateAssemblyCompanyAttributeField;
        
        private string generateAssemblyProductAttributeField;
        
        private string preserveCompilationContextField;
        
        private string assemblyNameField;
        
        private string packageIdField;
        
        private string userSecretsIdField;
        
        private string assetTargetFallbackField;
        
        private string runPostBuildEventField;
        
        private string startupObjectField;
        
        private string prefer32BitField;
        
        private string win32ResourceField;
        
        private string langVersionField;
        
        private string fileAlignmentField;
        
        private string errorReportField;
        
        private string configurationsField;
        
        private string runtimeIdentifierField;
        
        private string runtimeIdentifiersField;
        
        private string rootNamespaceField;
        
        private string optionExplicitField;
        
        private string optionCompareField;
        
        private string optionStrictField;
        
        private string optionInferField;
        
        private string noWarnField;
        
        private bool defineDebugField;
        
        private bool defineDebugFieldSpecified;
        
        private bool defineTraceField;
        
        private bool defineTraceFieldSpecified;
        
        private string conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DefineConstants {
            get {
                return this.defineConstantsField;
            }
            set {
                this.defineConstantsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlatformTarget {
            get {
                return this.platformTargetField;
            }
            set {
                this.platformTargetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AllowUnsafeBlocks {
            get {
                return this.allowUnsafeBlocksField;
            }
            set {
                this.allowUnsafeBlocksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Optimize {
            get {
                return this.optimizeField;
            }
            set {
                this.optimizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptimizeSpecified {
            get {
                return this.optimizeFieldSpecified;
            }
            set {
                this.optimizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TreatWarningsAsErrors {
            get {
                return this.treatWarningsAsErrorsField;
            }
            set {
                this.treatWarningsAsErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WarningsAsErrors {
            get {
                return this.warningsAsErrorsField;
            }
            set {
                this.warningsAsErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentationFile {
            get {
                return this.documentationFileField;
            }
            set {
                this.documentationFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GenerateSerializationAssemblies {
            get {
                return this.generateSerializationAssembliesField;
            }
            set {
                this.generateSerializationAssembliesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckForOverflowUnderflow {
            get {
                return this.checkForOverflowUnderflowField;
            }
            set {
                this.checkForOverflowUnderflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DebugType {
            get {
                return this.debugTypeField;
            }
            set {
                this.debugTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DebugSymbols {
            get {
                return this.debugSymbolsField;
            }
            set {
                this.debugSymbolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebugSymbolsSpecified {
            get {
                return this.debugSymbolsFieldSpecified;
            }
            set {
                this.debugSymbolsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputPath {
            get {
                return this.outputPathField;
            }
            set {
                this.outputPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public byte WarningLevel {
            get {
                return this.warningLevelField;
            }
            set {
                this.warningLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarningLevelSpecified {
            get {
                return this.warningLevelFieldSpecified;
            }
            set {
                this.warningLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OutputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFramework {
            get {
                return this.targetFrameworkField;
            }
            set {
                this.targetFrameworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TargetFrameworks {
            get {
                return this.targetFrameworksField;
            }
            set {
                this.targetFrameworksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EnableDefaultItems {
            get {
                return this.enableDefaultItemsField;
            }
            set {
                this.enableDefaultItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignAssembly {
            get {
                return this.signAssemblyField;
            }
            set {
                this.signAssemblyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssemblyOriginatorKeyFile {
            get {
                return this.assemblyOriginatorKeyFileField;
            }
            set {
                this.assemblyOriginatorKeyFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApplicationManifest {
            get {
                return this.applicationManifestField;
            }
            set {
                this.applicationManifestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageReleaseNotes {
            get {
                return this.packageReleaseNotesField;
            }
            set {
                this.packageReleaseNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageTags {
            get {
                return this.packageTagsField;
            }
            set {
                this.packageTagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RepositoryType {
            get {
                return this.repositoryTypeField;
            }
            set {
                this.repositoryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RepositoryUrl {
            get {
                return this.repositoryUrlField;
            }
            set {
                this.repositoryUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageIconUrl {
            get {
                return this.packageIconUrlField;
            }
            set {
                this.packageIconUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageProjectUrl {
            get {
                return this.packageProjectUrlField;
            }
            set {
                this.packageProjectUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageLicenseUrl {
            get {
                return this.packageLicenseUrlField;
            }
            set {
                this.packageLicenseUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssemblyVersion {
            get {
                return this.assemblyVersionField;
            }
            set {
                this.assemblyVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApplicationIcon {
            get {
                return this.applicationIconField;
            }
            set {
                this.applicationIconField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GeneratePackageOnBuild {
            get {
                return this.generatePackageOnBuildField;
            }
            set {
                this.generatePackageOnBuildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageRequireLicenseAcceptance {
            get {
                return this.packageRequireLicenseAcceptanceField;
            }
            set {
                this.packageRequireLicenseAcceptanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NeutralLanguage {
            get {
                return this.neutralLanguageField;
            }
            set {
                this.neutralLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileVersion {
            get {
                return this.fileVersionField;
            }
            set {
                this.fileVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MvcRazorCompileOnPublish {
            get {
                return this.mvcRazorCompileOnPublishField;
            }
            set {
                this.mvcRazorCompileOnPublishField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GenerateAssemblyConfigurationAttribute {
            get {
                return this.generateAssemblyConfigurationAttributeField;
            }
            set {
                this.generateAssemblyConfigurationAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GenerateAssemblyCompanyAttribute {
            get {
                return this.generateAssemblyCompanyAttributeField;
            }
            set {
                this.generateAssemblyCompanyAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GenerateAssemblyProductAttribute {
            get {
                return this.generateAssemblyProductAttributeField;
            }
            set {
                this.generateAssemblyProductAttributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PreserveCompilationContext {
            get {
                return this.preserveCompilationContextField;
            }
            set {
                this.preserveCompilationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserSecretsId {
            get {
                return this.userSecretsIdField;
            }
            set {
                this.userSecretsIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AssetTargetFallback {
            get {
                return this.assetTargetFallbackField;
            }
            set {
                this.assetTargetFallbackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RunPostBuildEvent {
            get {
                return this.runPostBuildEventField;
            }
            set {
                this.runPostBuildEventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StartupObject {
            get {
                return this.startupObjectField;
            }
            set {
                this.startupObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Prefer32Bit {
            get {
                return this.prefer32BitField;
            }
            set {
                this.prefer32BitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Win32Resource {
            get {
                return this.win32ResourceField;
            }
            set {
                this.win32ResourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LangVersion {
            get {
                return this.langVersionField;
            }
            set {
                this.langVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FileAlignment {
            get {
                return this.fileAlignmentField;
            }
            set {
                this.fileAlignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ErrorReport {
            get {
                return this.errorReportField;
            }
            set {
                this.errorReportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Configurations {
            get {
                return this.configurationsField;
            }
            set {
                this.configurationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RuntimeIdentifier {
            get {
                return this.runtimeIdentifierField;
            }
            set {
                this.runtimeIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RuntimeIdentifiers {
            get {
                return this.runtimeIdentifiersField;
            }
            set {
                this.runtimeIdentifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RootNamespace {
            get {
                return this.rootNamespaceField;
            }
            set {
                this.rootNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionExplicit {
            get {
                return this.optionExplicitField;
            }
            set {
                this.optionExplicitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionCompare {
            get {
                return this.optionCompareField;
            }
            set {
                this.optionCompareField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionStrict {
            get {
                return this.optionStrictField;
            }
            set {
                this.optionStrictField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OptionInfer {
            get {
                return this.optionInferField;
            }
            set {
                this.optionInferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoWarn {
            get {
                return this.noWarnField;
            }
            set {
                this.noWarnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DefineDebug {
            get {
                return this.defineDebugField;
            }
            set {
                this.defineDebugField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefineDebugSpecified {
            get {
                return this.defineDebugFieldSpecified;
            }
            set {
                this.defineDebugFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DefineTrace {
            get {
                return this.defineTraceField;
            }
            set {
                this.defineTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefineTraceSpecified {
            get {
                return this.defineTraceFieldSpecified;
            }
            set {
                this.defineTraceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroup {
        
        private ProjectItemGroupCompile[] compileField;
        
        private ProjectItemGroupDotNetCliToolReference[] dotNetCliToolReferenceField;
        
        private ProjectItemGroupFolder[] folderField;
        
        private ProjectItemGroupPackageReference[] packageReferenceField;
        
        private ProjectItemGroupReference[] referenceField;
        
        private ProjectItemGroupProjectReference[] projectReferenceField;
        
        private ProjectItemGroupEmbeddedResource[] embeddedResourceField;
        
        private ProjectItemGroupContent[] contentField;
        
        private ProjectItemGroupAdditionalFiles[] additionalFilesField;
        
        private ProjectItemGroupNone[] noneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Compile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupCompile[] Compile {
            get {
                return this.compileField;
            }
            set {
                this.compileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DotNetCliToolReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupDotNetCliToolReference[] DotNetCliToolReference {
            get {
                return this.dotNetCliToolReferenceField;
            }
            set {
                this.dotNetCliToolReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Folder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupFolder[] Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PackageReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupPackageReference[] PackageReference {
            get {
                return this.packageReferenceField;
            }
            set {
                this.packageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupReference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupProjectReference[] ProjectReference {
            get {
                return this.projectReferenceField;
            }
            set {
                this.projectReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmbeddedResource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupEmbeddedResource[] EmbeddedResource {
            get {
                return this.embeddedResourceField;
            }
            set {
                this.embeddedResourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupContent[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalFiles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupAdditionalFiles[] AdditionalFiles {
            get {
                return this.additionalFilesField;
            }
            set {
                this.additionalFilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("None", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectItemGroupNone[] None {
            get {
                return this.noneField;
            }
            set {
                this.noneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupCompile {
        
        private string generatorField;
        
        private string subTypeField;
        
        private bool designTimeField;
        
        private bool designTimeFieldSpecified;
        
        private bool autoGenField;
        
        private bool autoGenFieldSpecified;
        
        private string dependentUponField;
        
        private string copyToOutputDirectoryField;
        
        private string updateField;
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DesignTime {
            get {
                return this.designTimeField;
            }
            set {
                this.designTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DesignTimeSpecified {
            get {
                return this.designTimeFieldSpecified;
            }
            set {
                this.designTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AutoGen {
            get {
                return this.autoGenField;
            }
            set {
                this.autoGenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoGenSpecified {
            get {
                return this.autoGenFieldSpecified;
            }
            set {
                this.autoGenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DependentUpon {
            get {
                return this.dependentUponField;
            }
            set {
                this.dependentUponField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupDotNetCliToolReference {
        
        private string includeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupFolder {
        
        private string includeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupPackageReference {
        
        private string excludeAssetsField;
        
        private string includeAssetsField;
        
        private string privateAssetsField;
        
        private string noWarnField;
        
        private string includeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExcludeAssets {
            get {
                return this.excludeAssetsField;
            }
            set {
                this.excludeAssetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IncludeAssets {
            get {
                return this.includeAssetsField;
            }
            set {
                this.includeAssetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrivateAssets {
            get {
                return this.privateAssetsField;
            }
            set {
                this.privateAssetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoWarn {
            get {
                return this.noWarnField;
            }
            set {
                this.noWarnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupReference {
        
        private string hintPathField;
        
        private string embedInteropTypesField;
        
        private string aliasesField;
        
        private string privateField;
        
        private string includeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HintPath {
            get {
                return this.hintPathField;
            }
            set {
                this.hintPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmbedInteropTypes {
            get {
                return this.embedInteropTypesField;
            }
            set {
                this.embedInteropTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Private {
            get {
                return this.privateField;
            }
            set {
                this.privateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupProjectReference {
        
        private string aliasesField;
        
        private string privateField;
        
        private string includeField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aliases {
            get {
                return this.aliasesField;
            }
            set {
                this.aliasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Private {
            get {
                return this.privateField;
            }
            set {
                this.privateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupEmbeddedResource {
        
        private string generatorField;
        
        private string lastGenOutputField;
        
        private string copyToOutputDirectoryField;
        
        private string customToolNamespaceField;
        
        private string includeField;
        
        private string updateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastGenOutput {
            get {
                return this.lastGenOutputField;
            }
            set {
                this.lastGenOutputField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomToolNamespace {
            get {
                return this.customToolNamespaceField;
            }
            set {
                this.customToolNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupContent {
        
        private string copyToPublishDirectoryField;
        
        private string copyToOutputDirectoryField;
        
        private string includeField;
        
        private string updateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToPublishDirectory {
            get {
                return this.copyToPublishDirectoryField;
            }
            set {
                this.copyToPublishDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupAdditionalFiles {
        
        private string copyToOutputDirectoryField;
        
        private string generatorField;
        
        private string customToolNamespaceField;
        
        private string includeField;
        
        private string updateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomToolNamespace {
            get {
                return this.customToolNamespaceField;
            }
            set {
                this.customToolNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectItemGroupNone {
        
        private string copyToPublishDirectoryField;
        
        private string copyToOutputDirectoryField;
        
        private string generatorField;
        
        private string customToolNamespaceField;
        
        private string removeField;
        
        private string includeField;
        
        private string updateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToPublishDirectory {
            get {
                return this.copyToPublishDirectoryField;
            }
            set {
                this.copyToPublishDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomToolNamespace {
            get {
                return this.customToolNamespaceField;
            }
            set {
                this.customToolNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Remove {
            get {
                return this.removeField;
            }
            set {
                this.removeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectImport {
        
        private string projectField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectTarget {
        
        private ProjectTargetExec[] execField;
        
        private string nameField;
        
        private string beforeTargetsField;
        
        private string afterTargetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exec", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProjectTargetExec[] Exec {
            get {
                return this.execField;
            }
            set {
                this.execField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BeforeTargets {
            get {
                return this.beforeTargetsField;
            }
            set {
                this.beforeTargetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AfterTargets {
            get {
                return this.afterTargetsField;
            }
            set {
                this.afterTargetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ProjectTargetExec {
        
        private string commandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
}
