//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace JustDecompile.Tools.MSBuildProjectBuilder {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/developer/msbuild/2003", IsNullable=false)]
    public partial class Project {
        
        private object[] itemsField;
        
        private string defaultTargetsField;
        
        private decimal toolsVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Import", typeof(ProjectImport))]
        [System.Xml.Serialization.XmlElementAttribute("ItemGroup", typeof(ProjectItemGroup))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyGroup", typeof(ProjectPropertyGroup))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DefaultTargets {
            get {
                return this.defaultTargetsField;
            }
            set {
                this.defaultTargetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ToolsVersion {
            get {
                return this.toolsVersionField;
            }
            set {
                this.toolsVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectImport {
        
        private string projectField;
        
        private string conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroup {
        
        private ProjectItemGroupProjectReference projectReferenceField;
        
        private ProjectItemGroupFolder folderField;
        
        private ProjectItemGroupNone noneField;
        
        private ProjectItemGroupContent contentField;
        
        private ProjectItemGroupBootstrapperPackage[] bootstrapperPackageField;
        
        private ProjectItemGroupReference[] referenceField;
        
        private ProjectItemGroupAddModules[] addModulesField;
        
        private ProjectItemGroupCompile[] compileField;
        
        private ProjectItemGroupEmbeddedResource[] embeddedResourceField;
        
        private ProjectItemGroupApplicationDefinition applicationDefinitionField;
        
        private ProjectItemGroupPage[] pageField;
        
        private ProjectItemGroupResource[] resourceField;
        
        private ProjectItemGroupTargetPlatform[] targetPlatformField;
        
        /// <remarks/>
        public ProjectItemGroupProjectReference ProjectReference {
            get {
                return this.projectReferenceField;
            }
            set {
                this.projectReferenceField = value;
            }
        }
        
        /// <remarks/>
        public ProjectItemGroupFolder Folder {
            get {
                return this.folderField;
            }
            set {
                this.folderField = value;
            }
        }
        
        /// <remarks/>
        public ProjectItemGroupNone None {
            get {
                return this.noneField;
            }
            set {
                this.noneField = value;
            }
        }
        
        /// <remarks/>
        public ProjectItemGroupContent Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BootstrapperPackage")]
        public ProjectItemGroupBootstrapperPackage[] BootstrapperPackage {
            get {
                return this.bootstrapperPackageField;
            }
            set {
                this.bootstrapperPackageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ProjectItemGroupReference[] Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddModules")]
        public ProjectItemGroupAddModules[] AddModules {
            get {
                return this.addModulesField;
            }
            set {
                this.addModulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Compile")]
        public ProjectItemGroupCompile[] Compile {
            get {
                return this.compileField;
            }
            set {
                this.compileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmbeddedResource")]
        public ProjectItemGroupEmbeddedResource[] EmbeddedResource {
            get {
                return this.embeddedResourceField;
            }
            set {
                this.embeddedResourceField = value;
            }
        }
        
        /// <remarks/>
        public ProjectItemGroupApplicationDefinition ApplicationDefinition {
            get {
                return this.applicationDefinitionField;
            }
            set {
                this.applicationDefinitionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Page")]
        public ProjectItemGroupPage[] Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Resource")]
        public ProjectItemGroupResource[] Resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetPlatform")]
        public ProjectItemGroupTargetPlatform[] TargetPlatform {
            get {
                return this.targetPlatformField;
            }
            set {
                this.targetPlatformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupProjectReference {
        
        private string projectField;
        
        private string nameField;
        
        private string includeField;
        
        /// <remarks/>
        public string Project {
            get {
                return this.projectField;
            }
            set {
                this.projectField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupFolder {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupNone {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupContent {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupBootstrapperPackage {
        
        private string visibleField;
        
        private string productNameField;
        
        private bool installField;
        
        private string includeField;
        
        /// <remarks/>
        public string Visible {
            get {
                return this.visibleField;
            }
            set {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        public bool Install {
            get {
                return this.installField;
            }
            set {
                this.installField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupReference {
        
        private string itemField;
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HintPath")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupAddModules {
        
        private string includeField;
        
        private string conditionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupCompile {
        
        private string linkField;
        
        private bool autoGenField;
        
        private string dependentUponField;
        
        private bool designTimeSharedInputField;
        
        private string subTypeField;
        
        private string includeField;
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoGen {
            get {
                return this.autoGenField;
            }
            set {
                this.autoGenField = value;
            }
        }
        
        /// <remarks/>
        public string DependentUpon {
            get {
                return this.dependentUponField;
            }
            set {
                this.dependentUponField = value;
            }
        }
        
        /// <remarks/>
        public bool DesignTimeSharedInput {
            get {
                return this.designTimeSharedInputField;
            }
            set {
                this.designTimeSharedInputField = value;
            }
        }
        
        /// <remarks/>
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupEmbeddedResource {
        
        private string dependentUponField;
        
        private string generatorField;
        
        private string lastGenOutputField;
        
        private string customToolNamespaceField;
        
        private string linkField;
        
        private string subTypeField;
        
        private string copyToOutputDirectoryField;
        
        private string logicalNameField;
        
        private string includeField;
        
        /// <remarks/>
        public string DependentUpon {
            get {
                return this.dependentUponField;
            }
            set {
                this.dependentUponField = value;
            }
        }
        
        /// <remarks/>
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        public string LastGenOutput {
            get {
                return this.lastGenOutputField;
            }
            set {
                this.lastGenOutputField = value;
            }
        }
        
        /// <remarks/>
        public string CustomToolNamespace {
            get {
                return this.customToolNamespaceField;
            }
            set {
                this.customToolNamespaceField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CopyToOutputDirectory {
            get {
                return this.copyToOutputDirectoryField;
            }
            set {
                this.copyToOutputDirectoryField = value;
            }
        }
        
        /// <remarks/>
        public string LogicalName {
            get {
                return this.logicalNameField;
            }
            set {
                this.logicalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupApplicationDefinition {
        
        private string generatorField;
        
        private string subTypeField;
        
        private string includeField;
        
        /// <remarks/>
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupPage {
        
        private string generatorField;
        
        private string subTypeField;
        
        private string includeField;
        
        /// <remarks/>
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        public string SubType {
            get {
                return this.subTypeField;
            }
            set {
                this.subTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupResource {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectItemGroupTargetPlatform {
        
        private string includeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Include {
            get {
                return this.includeField;
            }
            set {
                this.includeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroup {
        
        private string preBuildEventField;
        
        private string postBuildEventField;
        
        private string outputPathField;
        
        private bool allowUnsafeBlocksField;
        
        private bool allowUnsafeBlocksFieldSpecified;
        
        private uint baseAddressField;
        
        private bool baseAddressFieldSpecified;
        
        private bool checkForOverflowUnderflowField;
        
        private bool checkForOverflowUnderflowFieldSpecified;
        
        private string configurationOverrideFileField;
        
        private bool debugSymbolsField;
        
        private bool debugSymbolsFieldSpecified;
        
        private string defineConstantsField;
        
        private bool defineDebugField;
        
        private bool defineDebugFieldSpecified;
        
        private bool defineTraceField;
        
        private bool defineTraceFieldSpecified;
        
        private string documentationFileField;
        
        private ushort fileAlignmentField;
        
        private bool fileAlignmentFieldSpecified;
        
        private bool noStdLibField;
        
        private bool noStdLibFieldSpecified;
        
        private bool noConfigField;
        
        private bool noConfigFieldSpecified;
        
        private string noWarnField;
        
        private bool optimizeField;
        
        private bool optimizeFieldSpecified;
        
        private bool registerForComInteropField;
        
        private bool registerForComInteropFieldSpecified;
        
        private bool removeIntegerChecksField;
        
        private bool removeIntegerChecksFieldSpecified;
        
        private bool treatWarningsAsErrorsField;
        
        private bool treatWarningsAsErrorsFieldSpecified;
        
        private byte warningLevelField;
        
        private bool warningLevelFieldSpecified;
        
        private string debugTypeField;
        
        private string errorReportField;
        
        private string codeAnalysisRuleSetField;
        
        private string productVersionField;
        
        private string projectGuidField;
        
        private string projectTypeField;
        
        private decimal schemaVersionField;
        
        private bool schemaVersionFieldSpecified;
        
        private ProjectPropertyGroupConfiguration configurationField;
        
        private ProjectPropertyGroupPlatform platformField;
        
        private string applicationIconField;
        
        private string assemblyKeyContainerNameField;
        
        private string assemblyNameField;
        
        private string assemblyOriginatorKeyFileField;
        
        private string defaultClientScriptField;
        
        private string defaultHTMLPageLayoutField;
        
        private string defaultTargetSchemaField;
        
        private bool delaySignField;
        
        private bool delaySignFieldSpecified;
        
        private string outputTypeField;
        
        private string appDesignerFolderField;
        
        private string rootNamespaceField;
        
        private string runPostBuildEventField;
        
        private string startupObjectField;
        
        private string fileUpgradeFlagsField;
        
        private string upgradeBackupLocationField;
        
        private decimal oldToolsVersionField;
        
        private bool oldToolsVersionFieldSpecified;
        
        private string targetFrameworkVersionField;
        
        private string publishUrlField;
        
        private bool installField;
        
        private bool installFieldSpecified;
        
        private string installFromField;
        
        private bool updateEnabledField;
        
        private bool updateEnabledFieldSpecified;
        
        private string updateModeField;
        
        private byte updateIntervalField;
        
        private bool updateIntervalFieldSpecified;
        
        private string updateIntervalUnitsField;
        
        private bool updatePeriodicallyField;
        
        private bool updatePeriodicallyFieldSpecified;
        
        private bool updateRequiredField;
        
        private bool updateRequiredFieldSpecified;
        
        private bool mapFileExtensionsField;
        
        private bool mapFileExtensionsFieldSpecified;
        
        private byte applicationRevisionField;
        
        private bool applicationRevisionFieldSpecified;
        
        private string applicationVersionField;
        
        private bool isWebBootstrapperField;
        
        private bool isWebBootstrapperFieldSpecified;
        
        private bool useApplicationTrustField;
        
        private bool useApplicationTrustFieldSpecified;
        
        private bool bootstrapperEnabledField;
        
        private bool bootstrapperEnabledFieldSpecified;
        
        private string sccProjectNameField;
        
        private string sccLocalPathField;
        
        private string sccAuxPathField;
        
        private string sccProviderField;
        
        private string platformTargetField;
        
        private string projectTypeGuidsField;
        
        private string visualStudioVersionField;
        
        private string minimumVisualStudioVersionField;
        
        private string targetPlatformVersionField;
        
        private string targetPlatformMinVersionField;
        
        private string targetFrameworkProfileField;
        
        private string targetPlatformIdentifierField;
        
        private bool useVSHostingProcessField;
        
        private bool useVSHostingProcessFieldSpecified;
        
        private bool prefer32BitField;
        
        private bool prefer32BitFieldSpecified;
        
        private string optionExplicitField;
        
        private string optionCompareField;
        
        private string optionStrictField;
        
        private string optionInferField;
        
        private bool autoGenerateBindingRedirectsField;
        
        private bool autoGenerateBindingRedirectsFieldSpecified;
        
        private bool allowCrossPlatformRetargetingField;
        
        private bool allowCrossPlatformRetargetingFieldSpecified;
        
        private bool useDotNetNativeToolchainField;
        
        private bool useDotNetNativeToolchainFieldSpecified;
        
        private string conditionField;
        
        /// <remarks/>
        public string PreBuildEvent {
            get {
                return this.preBuildEventField;
            }
            set {
                this.preBuildEventField = value;
            }
        }
        
        /// <remarks/>
        public string PostBuildEvent {
            get {
                return this.postBuildEventField;
            }
            set {
                this.postBuildEventField = value;
            }
        }
        
        /// <remarks/>
        public string OutputPath {
            get {
                return this.outputPathField;
            }
            set {
                this.outputPathField = value;
            }
        }
        
        /// <remarks/>
        public bool AllowUnsafeBlocks {
            get {
                return this.allowUnsafeBlocksField;
            }
            set {
                this.allowUnsafeBlocksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowUnsafeBlocksSpecified {
            get {
                return this.allowUnsafeBlocksFieldSpecified;
            }
            set {
                this.allowUnsafeBlocksFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint BaseAddress {
            get {
                return this.baseAddressField;
            }
            set {
                this.baseAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaseAddressSpecified {
            get {
                return this.baseAddressFieldSpecified;
            }
            set {
                this.baseAddressFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool CheckForOverflowUnderflow {
            get {
                return this.checkForOverflowUnderflowField;
            }
            set {
                this.checkForOverflowUnderflowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckForOverflowUnderflowSpecified {
            get {
                return this.checkForOverflowUnderflowFieldSpecified;
            }
            set {
                this.checkForOverflowUnderflowFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ConfigurationOverrideFile {
            get {
                return this.configurationOverrideFileField;
            }
            set {
                this.configurationOverrideFileField = value;
            }
        }
        
        /// <remarks/>
        public bool DebugSymbols {
            get {
                return this.debugSymbolsField;
            }
            set {
                this.debugSymbolsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebugSymbolsSpecified {
            get {
                return this.debugSymbolsFieldSpecified;
            }
            set {
                this.debugSymbolsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DefineConstants {
            get {
                return this.defineConstantsField;
            }
            set {
                this.defineConstantsField = value;
            }
        }
        
        /// <remarks/>
        public bool DefineDebug {
            get {
                return this.defineDebugField;
            }
            set {
                this.defineDebugField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefineDebugSpecified {
            get {
                return this.defineDebugFieldSpecified;
            }
            set {
                this.defineDebugFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool DefineTrace {
            get {
                return this.defineTraceField;
            }
            set {
                this.defineTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DefineTraceSpecified {
            get {
                return this.defineTraceFieldSpecified;
            }
            set {
                this.defineTraceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DocumentationFile {
            get {
                return this.documentationFileField;
            }
            set {
                this.documentationFileField = value;
            }
        }
        
        /// <remarks/>
        public ushort FileAlignment {
            get {
                return this.fileAlignmentField;
            }
            set {
                this.fileAlignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileAlignmentSpecified {
            get {
                return this.fileAlignmentFieldSpecified;
            }
            set {
                this.fileAlignmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool NoStdLib {
            get {
                return this.noStdLibField;
            }
            set {
                this.noStdLibField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoStdLibSpecified {
            get {
                return this.noStdLibFieldSpecified;
            }
            set {
                this.noStdLibFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool NoConfig {
            get {
                return this.noConfigField;
            }
            set {
                this.noConfigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoConfigSpecified {
            get {
                return this.noConfigFieldSpecified;
            }
            set {
                this.noConfigFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string NoWarn {
            get {
                return this.noWarnField;
            }
            set {
                this.noWarnField = value;
            }
        }
        
        /// <remarks/>
        public bool Optimize {
            get {
                return this.optimizeField;
            }
            set {
                this.optimizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptimizeSpecified {
            get {
                return this.optimizeFieldSpecified;
            }
            set {
                this.optimizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RegisterForComInterop {
            get {
                return this.registerForComInteropField;
            }
            set {
                this.registerForComInteropField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterForComInteropSpecified {
            get {
                return this.registerForComInteropFieldSpecified;
            }
            set {
                this.registerForComInteropFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool RemoveIntegerChecks {
            get {
                return this.removeIntegerChecksField;
            }
            set {
                this.removeIntegerChecksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemoveIntegerChecksSpecified {
            get {
                return this.removeIntegerChecksFieldSpecified;
            }
            set {
                this.removeIntegerChecksFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool TreatWarningsAsErrors {
            get {
                return this.treatWarningsAsErrorsField;
            }
            set {
                this.treatWarningsAsErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TreatWarningsAsErrorsSpecified {
            get {
                return this.treatWarningsAsErrorsFieldSpecified;
            }
            set {
                this.treatWarningsAsErrorsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte WarningLevel {
            get {
                return this.warningLevelField;
            }
            set {
                this.warningLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarningLevelSpecified {
            get {
                return this.warningLevelFieldSpecified;
            }
            set {
                this.warningLevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string DebugType {
            get {
                return this.debugTypeField;
            }
            set {
                this.debugTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorReport {
            get {
                return this.errorReportField;
            }
            set {
                this.errorReportField = value;
            }
        }
        
        /// <remarks/>
        public string CodeAnalysisRuleSet {
            get {
                return this.codeAnalysisRuleSetField;
            }
            set {
                this.codeAnalysisRuleSetField = value;
            }
        }
        
        /// <remarks/>
        public string ProductVersion {
            get {
                return this.productVersionField;
            }
            set {
                this.productVersionField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectGuid {
            get {
                return this.projectGuidField;
            }
            set {
                this.projectGuidField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectType {
            get {
                return this.projectTypeField;
            }
            set {
                this.projectTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal SchemaVersion {
            get {
                return this.schemaVersionField;
            }
            set {
                this.schemaVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SchemaVersionSpecified {
            get {
                return this.schemaVersionFieldSpecified;
            }
            set {
                this.schemaVersionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ProjectPropertyGroupConfiguration Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        public ProjectPropertyGroupPlatform Platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationIcon {
            get {
                return this.applicationIconField;
            }
            set {
                this.applicationIconField = value;
            }
        }
        
        /// <remarks/>
        public string AssemblyKeyContainerName {
            get {
                return this.assemblyKeyContainerNameField;
            }
            set {
                this.assemblyKeyContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public string AssemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
        
        /// <remarks/>
        public string AssemblyOriginatorKeyFile {
            get {
                return this.assemblyOriginatorKeyFileField;
            }
            set {
                this.assemblyOriginatorKeyFileField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultClientScript {
            get {
                return this.defaultClientScriptField;
            }
            set {
                this.defaultClientScriptField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultHTMLPageLayout {
            get {
                return this.defaultHTMLPageLayoutField;
            }
            set {
                this.defaultHTMLPageLayoutField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultTargetSchema {
            get {
                return this.defaultTargetSchemaField;
            }
            set {
                this.defaultTargetSchemaField = value;
            }
        }
        
        /// <remarks/>
        public bool DelaySign {
            get {
                return this.delaySignField;
            }
            set {
                this.delaySignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DelaySignSpecified {
            get {
                return this.delaySignFieldSpecified;
            }
            set {
                this.delaySignFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OutputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AppDesignerFolder {
            get {
                return this.appDesignerFolderField;
            }
            set {
                this.appDesignerFolderField = value;
            }
        }
        
        /// <remarks/>
        public string RootNamespace {
            get {
                return this.rootNamespaceField;
            }
            set {
                this.rootNamespaceField = value;
            }
        }
        
        /// <remarks/>
        public string RunPostBuildEvent {
            get {
                return this.runPostBuildEventField;
            }
            set {
                this.runPostBuildEventField = value;
            }
        }
        
        /// <remarks/>
        public string StartupObject {
            get {
                return this.startupObjectField;
            }
            set {
                this.startupObjectField = value;
            }
        }
        
        /// <remarks/>
        public string FileUpgradeFlags {
            get {
                return this.fileUpgradeFlagsField;
            }
            set {
                this.fileUpgradeFlagsField = value;
            }
        }
        
        /// <remarks/>
        public string UpgradeBackupLocation {
            get {
                return this.upgradeBackupLocationField;
            }
            set {
                this.upgradeBackupLocationField = value;
            }
        }
        
        /// <remarks/>
        public decimal OldToolsVersion {
            get {
                return this.oldToolsVersionField;
            }
            set {
                this.oldToolsVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OldToolsVersionSpecified {
            get {
                return this.oldToolsVersionFieldSpecified;
            }
            set {
                this.oldToolsVersionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TargetFrameworkVersion {
            get {
                return this.targetFrameworkVersionField;
            }
            set {
                this.targetFrameworkVersionField = value;
            }
        }
        
        /// <remarks/>
        public string PublishUrl {
            get {
                return this.publishUrlField;
            }
            set {
                this.publishUrlField = value;
            }
        }
        
        /// <remarks/>
        public bool Install {
            get {
                return this.installField;
            }
            set {
                this.installField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstallSpecified {
            get {
                return this.installFieldSpecified;
            }
            set {
                this.installFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string InstallFrom {
            get {
                return this.installFromField;
            }
            set {
                this.installFromField = value;
            }
        }
        
        /// <remarks/>
        public bool UpdateEnabled {
            get {
                return this.updateEnabledField;
            }
            set {
                this.updateEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateEnabledSpecified {
            get {
                return this.updateEnabledFieldSpecified;
            }
            set {
                this.updateEnabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string UpdateMode {
            get {
                return this.updateModeField;
            }
            set {
                this.updateModeField = value;
            }
        }
        
        /// <remarks/>
        public byte UpdateInterval {
            get {
                return this.updateIntervalField;
            }
            set {
                this.updateIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateIntervalSpecified {
            get {
                return this.updateIntervalFieldSpecified;
            }
            set {
                this.updateIntervalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string UpdateIntervalUnits {
            get {
                return this.updateIntervalUnitsField;
            }
            set {
                this.updateIntervalUnitsField = value;
            }
        }
        
        /// <remarks/>
        public bool UpdatePeriodically {
            get {
                return this.updatePeriodicallyField;
            }
            set {
                this.updatePeriodicallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdatePeriodicallySpecified {
            get {
                return this.updatePeriodicallyFieldSpecified;
            }
            set {
                this.updatePeriodicallyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool UpdateRequired {
            get {
                return this.updateRequiredField;
            }
            set {
                this.updateRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateRequiredSpecified {
            get {
                return this.updateRequiredFieldSpecified;
            }
            set {
                this.updateRequiredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool MapFileExtensions {
            get {
                return this.mapFileExtensionsField;
            }
            set {
                this.mapFileExtensionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MapFileExtensionsSpecified {
            get {
                return this.mapFileExtensionsFieldSpecified;
            }
            set {
                this.mapFileExtensionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public byte ApplicationRevision {
            get {
                return this.applicationRevisionField;
            }
            set {
                this.applicationRevisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationRevisionSpecified {
            get {
                return this.applicationRevisionFieldSpecified;
            }
            set {
                this.applicationRevisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationVersion {
            get {
                return this.applicationVersionField;
            }
            set {
                this.applicationVersionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsWebBootstrapper {
            get {
                return this.isWebBootstrapperField;
            }
            set {
                this.isWebBootstrapperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsWebBootstrapperSpecified {
            get {
                return this.isWebBootstrapperFieldSpecified;
            }
            set {
                this.isWebBootstrapperFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool UseApplicationTrust {
            get {
                return this.useApplicationTrustField;
            }
            set {
                this.useApplicationTrustField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseApplicationTrustSpecified {
            get {
                return this.useApplicationTrustFieldSpecified;
            }
            set {
                this.useApplicationTrustFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool BootstrapperEnabled {
            get {
                return this.bootstrapperEnabledField;
            }
            set {
                this.bootstrapperEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BootstrapperEnabledSpecified {
            get {
                return this.bootstrapperEnabledFieldSpecified;
            }
            set {
                this.bootstrapperEnabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SccProjectName {
            get {
                return this.sccProjectNameField;
            }
            set {
                this.sccProjectNameField = value;
            }
        }
        
        /// <remarks/>
        public string SccLocalPath {
            get {
                return this.sccLocalPathField;
            }
            set {
                this.sccLocalPathField = value;
            }
        }
        
        /// <remarks/>
        public string SccAuxPath {
            get {
                return this.sccAuxPathField;
            }
            set {
                this.sccAuxPathField = value;
            }
        }
        
        /// <remarks/>
        public string SccProvider {
            get {
                return this.sccProviderField;
            }
            set {
                this.sccProviderField = value;
            }
        }
        
        /// <remarks/>
        public string PlatformTarget {
            get {
                return this.platformTargetField;
            }
            set {
                this.platformTargetField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectTypeGuids {
            get {
                return this.projectTypeGuidsField;
            }
            set {
                this.projectTypeGuidsField = value;
            }
        }
        
        /// <remarks/>
        public string VisualStudioVersion {
            get {
                return this.visualStudioVersionField;
            }
            set {
                this.visualStudioVersionField = value;
            }
        }
        
        /// <remarks/>
        public string MinimumVisualStudioVersion {
            get {
                return this.minimumVisualStudioVersionField;
            }
            set {
                this.minimumVisualStudioVersionField = value;
            }
        }
        
        /// <remarks/>
        public string TargetPlatformVersion {
            get {
                return this.targetPlatformVersionField;
            }
            set {
                this.targetPlatformVersionField = value;
            }
        }
        
        /// <remarks/>
        public string TargetPlatformMinVersion {
            get {
                return this.targetPlatformMinVersionField;
            }
            set {
                this.targetPlatformMinVersionField = value;
            }
        }
        
        /// <remarks/>
        public string TargetFrameworkProfile {
            get {
                return this.targetFrameworkProfileField;
            }
            set {
                this.targetFrameworkProfileField = value;
            }
        }
        
        /// <remarks/>
        public string TargetPlatformIdentifier {
            get {
                return this.targetPlatformIdentifierField;
            }
            set {
                this.targetPlatformIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public bool UseVSHostingProcess {
            get {
                return this.useVSHostingProcessField;
            }
            set {
                this.useVSHostingProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseVSHostingProcessSpecified {
            get {
                return this.useVSHostingProcessFieldSpecified;
            }
            set {
                this.useVSHostingProcessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Prefer32Bit {
            get {
                return this.prefer32BitField;
            }
            set {
                this.prefer32BitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prefer32BitSpecified {
            get {
                return this.prefer32BitFieldSpecified;
            }
            set {
                this.prefer32BitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OptionExplicit {
            get {
                return this.optionExplicitField;
            }
            set {
                this.optionExplicitField = value;
            }
        }
        
        /// <remarks/>
        public string OptionCompare {
            get {
                return this.optionCompareField;
            }
            set {
                this.optionCompareField = value;
            }
        }
        
        /// <remarks/>
        public string OptionStrict {
            get {
                return this.optionStrictField;
            }
            set {
                this.optionStrictField = value;
            }
        }
        
        /// <remarks/>
        public string OptionInfer {
            get {
                return this.optionInferField;
            }
            set {
                this.optionInferField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoGenerateBindingRedirects {
            get {
                return this.autoGenerateBindingRedirectsField;
            }
            set {
                this.autoGenerateBindingRedirectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AutoGenerateBindingRedirectsSpecified {
            get {
                return this.autoGenerateBindingRedirectsFieldSpecified;
            }
            set {
                this.autoGenerateBindingRedirectsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool AllowCrossPlatformRetargeting {
            get {
                return this.allowCrossPlatformRetargetingField;
            }
            set {
                this.allowCrossPlatformRetargetingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AllowCrossPlatformRetargetingSpecified {
            get {
                return this.allowCrossPlatformRetargetingFieldSpecified;
            }
            set {
                this.allowCrossPlatformRetargetingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool UseDotNetNativeToolchain {
            get {
                return this.useDotNetNativeToolchainField;
            }
            set {
                this.useDotNetNativeToolchainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseDotNetNativeToolchainSpecified {
            get {
                return this.useDotNetNativeToolchainFieldSpecified;
            }
            set {
                this.useDotNetNativeToolchainFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroupConfiguration {
        
        private string conditionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/developer/msbuild/2003")]
    public partial class ProjectPropertyGroupPlatform {
        
        private string conditionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
